version: "3.7"
services: 
    springboot:
        image: openjdk:12
        environment:
            - SPRING_BOOT_PORT=8080
        ports:
            - "8080:8080"
        volumes:
            - ./fruits-impl/target/fruits-impl-1.0.0.jar:/app.jar
        # https://docs.docker.com/compose/compose-file/#entrypoint
        entrypoint: ["java","-jar","/app.jar"]

