version: "3.7"
services: 
    springboot:
        image: openjdk
        environment:
            - SPRING_BOOT_PORT=8080
        ports:
            - "8080:8080"
        #volumes: # TODO copier jar
        # https://docs.docker.com/compose/compose-file/#entrypoint
        entrypoint: ["java","-jar","/app.jar"]

